env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  comma-dangle:
    - off
  indent:
    - error
    - 2
    - SwitchCase: 2
  linebreak-style:
    - error
    - unix
  no-console:
    - off
  quotes:
    - error
    - single
  semi:
    - error
    - always
