#!/bin/bash
set -e


SOURCE_FILE=$1
if [ -z "$SOURCE_FILE" ]; then
  echo "Must provide source file as first argument"
  exit 1
fi

SOURCE_CONTENTS=$(cat "$SOURCE_FILE")

printf '// ==UserScript==
// @name         Gmail Simple
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Spruces up the basic HTML version of gmail to make it look nicer and function better with vimium.
// @author       CrisFeo
// @match        https://mail.google.com/mail/u/*/h/*
// @grant        none
// ==/UserScript==

%s' "$SOURCE_CONTENTS"
