#!/bin/bash
set -e

# Renders a Tampermoney userscript using the provided style and source files to
# standard out.

CSS_FILE=$1
if [ -z "$CSS_FILE" ]; then
  echo "Must provide css file as first argument"
  exit 1
fi

JS_FILE=$2
if [ -z "$JS_FILE" ]; then
  echo "Must provide js file as second argument"
  exit 1
fi

# Read the input files, escaping and removing newlines in the CSS.
CSS_CONTENTS=$(sed 's#"#\\"#g' < "$CSS_FILE" | tr -d '\n\r')
JS_CONTENTS=$(cat "$JS_FILE")

printf '// ==UserScript==
// @name         Gmail Simple
// @namespace    https://github.com/CrisFeo/gmail-simple
// @@downloadURL https://raw.githubusercontent.com/CrisFeo/gmail-simple/master/dist/gmail-simple.user.js
// @version      1.0.0
// @description  Spruces up the basic HTML version of gmail to make it look nicer and function better with vimium.
// @author       CrisFeo
// @match        https://mail.google.com/mail/u/*/h/*
// @grant        none
// ==/UserScript==

// Bundled styles
(function(){
  var s = document.createElement("style");
  s.type = "text/css";
  s.innerHTML = "%s";
  (document.head || document.documentElement).appendChild(s);
})();

// Bundled code
%s' "$CSS_CONTENTS" "$JS_CONTENTS"
